server:
  port: 8080

spring:
  application:
    name: tacocloud
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
  datasource:
    url: jdbc:postgresql://taco-db:5432/taco
    username: taco
    password: taco
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
