spring.application.name=tacocloud
spring.thymeleaf.cache=false
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://127.0.0.1:15432/taco
spring.datasource.username=taco
spring.datasource.password=taco
spring.datasource.driver-class-name=org.postgresql.Driver